### PR TITLE
feat: fix different types of role definition wrong g function

### LINKED ISSUE #1306: [Bug] Different types of role definition wrong g function
**Want to prioritize this issue? Try:**

[issuehunt-to-marktext](https://issuehunt.io/r/casbin/casbin)

------

**Describe the bug**
G function will be override by wrong generated g function if we have at least *2* different types role definition.

https://github.com/casbin/casbin/blob/e46d08ee10207a3fd89972e40590f794612e27d1/enforcer.go#L584-L594

**To Reproduce**
https://go.dev/play/p/blXW5-bZ1ZA

**Screenshots**
image

image

### PR DESCRIPTION
**Pull request by mtt0**
Fix #1306

### CODE REVIEW

File: enforcer.go [hunk 1]
```diff
@@ -584,10 +584,13 @@ func (e *Enforcer) enforce(matcher string, explains *[]string, rvals ...interfac
...
+			// g must be a normal role definition (ast.RM != nil)
+			//   or a conditional role definition (ast.CondRM != nil)
+			// ast.RM and ast.CondRM shouldn't be nil at the same time
+			if ast.RM != nil {
 				functions[key] = util.GenerateGFunction(ast.RM)
 			}
-			if len(e.condRmMap) != 0 {
+			if ast.CondRM != nil {
 				functions[key] = util.GenerateConditionalGFunction(ast.CondRM)
 			}
```
Comment (mtt0) [inline enforcer.go:595]:
```golang
			// g is a conditional role definition
			if len(e.condRmMap) != 0 && ast.CondRM != nil {
				functions[key] = util.GenerateConditionalGFunction(ast.CondRM)
			}
			// or g is a normal role definition
			// g must be a conditional role definition or a normal role definition
			// so equals to `len(e.rmMap) != 0 && ast.RM != nil`
			//    equals to `ast.RM != nil`
			if len(e.rmMap) != 0 && (ast.RM != nil || functions[key] == nil) {
				functions[key] = util.GenerateGFunction(ast.RM)
			}
```

Not sure which one is more readable. `len(e.rmMap)` only indicates that we have at least 1 role definition, so `ast.RM` is better. And `ast.RM != nil` is more clear.

Comment (PokIsemaine) [reply enforcer.go:595]: @mtt0 Good job! 
`ast.RM != nil` looks more readable, but there are some tests that don't pass at the moment, please fix this.
image

It looks like this is when our `AddDef` didn't update `ast.RM` and `ast.CondRM`, you can try to update them in `AddDef` like `initRmMap`

```golang
	if sec == "r" || sec == "p" {
		ast.Tokens = strings.Split(ast.Value, ",")
		for i := range ast.Tokens {
			ast.Tokens[i] = key + "_" + strings.TrimSpace(ast.Tokens[i])
		}
	} else if sec == "g" {
		ast.ParamsTokens = getParamsToken(ast.Value)
		ast.Tokens = strings.Split(ast.Value, ",")
		ast.Tokens = ast.Tokens[:len(ast.Tokens)-len(ast.ParamsTokens)]
		if len(ast.Tokens) <= 2 && len(ast.ParamsTokens) == 0 {
			ast.RM = defaultrolemanager.NewRoleManagerImpl(10)
		} else if len(ast.Tokens) <= 2 && len(ast.ParamsTokens) != 0 {
			ast.CondRM = defaultrolemanager.NewConditionalRoleManager(10)
		} else if len(ast.Tokens) > 2 && len(ast.ParamsTokens) == 0 {
			ast.RM = defaultrolemanager.NewRoleManager(10)
		} else if len(ast.Tokens) > 2 && len(ast.ParamsTokens) != 0 {
			ast.CondRM = defaultrolemanager.NewConditionalDomainManager(10)
		}
	} else {
		ast.Value = util.RemoveComments(util.EscapeAssertion(ast.Value))
	}
```

By the way, if you are convenient, you can add some test cases of different types of role definition, thank you very much for your contribution!

**Comment by hsluoyz** [comment]
@mtt0 plz fix:

image

File: enforcer.go (hunk 1 above)
Comment (mtt0) [reply enforcer.go:599]: Done. I tried insert codes below:

```golang
		if len(ast.Tokens) <= 2 && len(ast.ParamsTokens) == 0 {
			ast.RM = defaultrolemanager.NewRoleManagerImpl(10)
		}
		if len(ast.Tokens) <= 2 && len(ast.ParamsTokens) != 0 {
			ast.CondRM = defaultrolemanager.NewConditionalRoleManager(10)
		}
		if len(ast.Tokens) > 2 {
			if len(ast.ParamsTokens) == 0 {
				ast.RM = defaultrolemanager.NewRoleManager(10)
			} else {
				ast.CondRM = defaultrolemanager.NewConditionalDomainManager(10)
			}
			matchFun := "keyMatch(r_dom, p_dom)"
			if strings.Contains(model["m"]["m"].Value, matchFun) {
				ast.RM.AddDomainMatchingFunc("g", util.KeyMatch)
			}
		}
```

after `AddDef` L90:
https://github.com/casbin/casbin/blob/e46d08ee10207a3fd89972e40590f794612e27d1/model/model.go#L87C1-L91.

It works fine. But I prefer to try to make a function do only one thing, because the code is similar, if you modify one of them in the future, it is easy to forget that the other may also need a similar modification. What's more, users must call `e.Enforce` which will finally call `e.initRmMap`, but users may not call `AddDef`.

Comment (PokIsemaine) [reply enforcer.go:599]: That's right, your design is even better.

File: model_test.go [hunk 2]
```diff
@@ -349,8 +349,8 @@ func TestRBACModelWithDifferentTypesOfRoles(t *testing.T) {
 	testEnforce(t, e, "bob", "data1", "write", false)
 	testEnforce(t, e, "bob", "data2", "read", true)
 	testEnforce(t, e, "bob", "data2", "write", false)
-	testEnforce(t, e, "carol", "data2", "read", false)
-	testEnforce(t, e, "carol", "data2", "write", false)
+	testEnforce(t, e, "carol", "data1", "read", false)
```
Comment (mtt0) [inline model_test.go:352]: Fix enforce

**Comment by mtt0** [comment]
Please review when you are avaliable, I think it's ready to merge.
